---
name: enos_fmt

on:
  pull_request:
    paths:
      - enos/**

permissions:
  contents: read

jobs:
  fmt_check:
    # Only run this workflow on pull requests from hashicorp/boundary branches
    # as we need secrets to install enos.
    if: "! github.event.pull_request.head.repo.fork"
    runs-on: ${{ fromJSON(vars.RUNNER) }}
    env:
      GITHUB_TOKEN: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1    # TSCCR: loading action configs: failed to query HEAD reference: failed to get advertised references: authorization failed
        with:
          terraform_wrapper: false
      - uses: hashicorp/action-setup-enos@v1    # TSCCR: loading action configs: failed to query HEAD reference: failed to get advertised references: authorization failed
        with:
          github-token: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
      - name: "check formatting"
        working-directory: ./enos
        run: make check-fmt
