---
name: enos_fmt

on:
  pull_request:
    paths:
      - enos/**

permissions:
  contents: read

jobs:
  fmt_check:
    # Only run this workflow on pull requests from hashicorp/boundary branches
    # as we need secrets to install enos.
    if: github.event.pull_request.head.repo.fork != 'true'
    runs-on: ${{ fromJSON(vars.RUNNER) }}
    env:
      GITHUB_TOKEN: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36    # TSCCR: loading action configs: failed to query HEAD reference: failed to get advertised references: authorization failed
        with:
          terraform_wrapper: false
      - uses: hashicorp/action-setup-enos@v1    # TSCCR: loading action configs: failed to query HEAD reference: failed to get advertised references: authorization failed
        with:
          github-token: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
      - name: "check formatting"
        working-directory: ./enos
        run: make check-fmt
