---
name: enos_fmt

on:
  pull_request:
    paths:
      - enos/**

permissions:
  contents: read

jobs:
  fmt_check:
    # Only run this workflow on pull requests from hashicorp/boundary branches
    # as we need secrets to install enos.
    if: github.event.pull_request.head.repo.fork != 'true'
    runs-on: ${{ fromJSON(vars.RUNNER) }}
    env:
      GITHUB_TOKEN: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85    # TSCCR: loading action configs: failed to query HEAD reference: failed to get advertised references: authorization failed
        with:
          terraform_wrapper: false
      - uses: hashicorp/action-setup-enos@v1    # TSCCR: loading action configs: failed to query HEAD reference: failed to get advertised references: authorization failed
        with:
          github-token: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
      - name: "check formatting"
        working-directory: ./enos
        run: make check-fmt
