# This workflow checks that there is either a 'pr/no-milestone' label applied
# to a PR or there is a milestone associated with a PR

name: Check Milestone

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    # Runs on PRs to main and release branches
    branches:
      - main
      - release/**

permissions:
  contents: read
  statuses: write

jobs:
  # checks that a milestone entry is present for a PR
  milestone-check:
    # If there is a `pr/no-milestone` label we ignore this check
    if: contains(github.event.pull_request.labels.*.name, 'pr/no-milestone') != true
    runs-on: ${{ fromJSON(vars.RUNNER) }}
    steps:
      - name: Checkout Actions
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: 3e07b3b88b3984f28067a76dce5a052f0c5d3c73
      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '16.x'
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run PR Checks
        uses: ./actions/pr-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configPath: configs/milestone-check
