name: test-sql

on:
  push:
    paths-ignore:
      - 'website/**'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-sql:
    runs-on: ${{ fromJSON(vars.RUNNER) }}
    strategy:
      matrix:
        postgres-version: [ alpine, 13-alpine, 14-alpine, 15-alpine, 16-alpine, 17-alpine ]
    name: SQL Tests ${{ matrix.postgres-version }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Run SQL PgTap Tests
        run: |
          make test-sql POSTGRES_DOCKER_IMAGE_BASE=docker.mirror.hashicorp.services/postgres PG_DOCKER_TAG=${{ matrix.postgres-version }}
