name: test-sql

on:
  - workflow_dispatch
  - push
  - workflow_call

permissions:
  contents: read

jobs:
  test-sql:
    runs-on: ${{ fromJSON(vars.RUNNER) }}
    strategy:
      matrix:
        postgres-version: [ latest, 11-alpine, 12-alpine, 13-alpine, 14-alpine, 15-alpine ]
    name: SQL Tests ${{ matrix.postgres-version }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Run SQL PgTap Tests
        run: |
          make test-sql POSTGRES_DOCKER_IMAGE_BASE=docker.mirror.hashicorp.services/postgres PG_DOCKER_TAG=${{ matrix.postgres-version }}
