name: test-sql

on:
  push:
    paths-ignore:
      - 'website/**'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-sql:
    runs-on: ${{ fromJSON(vars.RUNNER) }}
    strategy:
      matrix:
        postgres-version: [ alpine,15-alpine, 16-alpine, 17-alpine ]
    name: SQL Tests ${{ matrix.postgres-version }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Run SQL PgTap Tests
        run: |
          make test-sql POSTGRES_DOCKER_IMAGE_BASE=docker.mirror.hashicorp.services/postgres PG_DOCKER_TAG=${{ matrix.postgres-version }}
